# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "c2OJf8iITVme1seW4nTummbr/71iFTQIxWSZlqpzQflpK6wb+WMdD5QolPPMFiVsAFt2wEEx4sxUNfeJWv4MVanCx6hbf+1IwircR+hJXL6SPnz88/O3hLZYNvSSzJwia6GAIWiSKYMxTns3jpeT0/mROv4FRkOspyJkBi454c0RmvJA9Fd6gwigeAwUhc0sMbwRaFBmlD1xBc76jolGGHe35adbtYUSmmEbPFkqJ3cI0yzju4c35u+/61Esjb8MdFKrVHcJot5g97bDva8niI/rq8R383ZtZmyl1sOieduM1Caut8NBWeMN9lRPTz/y8pkqmxWGec8FZqem/zNZLzDKe2t6Z95p7587175ICEkCaUnq4UYiUtBiWrhwaSP4OTbKWwCXsC/nV1TxTa2ph//181j3yXbzabUacsIlvg579aaN7sGj8SGSJSB1x5Z1hT974Oc0l5lgAtabZ0RPA+rD7NnOArobZlhdJaDZEo8xhBJbHVe1opr0gBQkhc7vOHK6Njl4YSGor8547yTL37X2djR5OxWX/TNKwAhE398BDCctbF2a3aK7C2espT8oqX9OUY8yOFIzBqiP7DwCDnvNb14ny77W83QZoPduP9gPoYb/ui1qfp68pZ3FN8u87IZWkghhjR2ZOvXqsdJvZhUxlJYmXpVkLaisBEK4Aw0="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
