travis:
  secure:
    BINSTAR_TOKEN: c2OJf8iITVme1seW4nTummbr/71iFTQIxWSZlqpzQflpK6wb+WMdD5QolPPMFiVsAFt2wEEx4sxUNfeJWv4MVanCx6hbf+1IwircR+hJXL6SPnz88/O3hLZYNvSSzJwia6GAIWiSKYMxTns3jpeT0/mROv4FRkOspyJkBi454c0RmvJA9Fd6gwigeAwUhc0sMbwRaFBmlD1xBc76jolGGHe35adbtYUSmmEbPFkqJ3cI0yzju4c35u+/61Esjb8MdFKrVHcJot5g97bDva8niI/rq8R383ZtZmyl1sOieduM1Caut8NBWeMN9lRPTz/y8pkqmxWGec8FZqem/zNZLzDKe2t6Z95p7587175ICEkCaUnq4UYiUtBiWrhwaSP4OTbKWwCXsC/nV1TxTa2ph//181j3yXbzabUacsIlvg579aaN7sGj8SGSJSB1x5Z1hT974Oc0l5lgAtabZ0RPA+rD7NnOArobZlhdJaDZEo8xhBJbHVe1opr0gBQkhc7vOHK6Njl4YSGor8547yTL37X2djR5OxWX/TNKwAhE398BDCctbF2a3aK7C2espT8oqX9OUY8yOFIzBqiP7DwCDnvNb14ny77W83QZoPduP9gPoYb/ui1qfp68pZ3FN8u87IZWkghhjR2ZOvXqsdJvZhUxlJYmXpVkLaisBEK4Aw0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
